# Generated by Django 4.2.11 on 2024-11-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0010_estudio_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='idpaciente',
            field=models.IntegerField(default='0', verbose_name='idpaciente'),
        ),
    ]
