# Generated by Django 4.2.11 on 2024-11-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0012_remove_estudio_idpaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='aliaspaciente',
            field=models.CharField(default='no', max_length=30),
        ),
    ]
