# Generated by Django 4.2.11 on 2024-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Sim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('medico', models.CharField(max_length=30)),
                ('paciente', models.CharField(max_length=30)),
                ('estudio1', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=30)),
            ],
        ),
    ]
