# Generated by Django 4.2.11 on 2024-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_sim',
            name='fecha_estudio',
            field=models.DateTimeField(auto_now=True, verbose_name='date joined'),
        ),
    ]
