# Generated by Django 4.2.11 on 2024-11-06 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0003_remove_form_sim_fecha_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_sim',
            name='fecha_estudio',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date joined'),
        ),
    ]
