# Generated by Django 4.2.11 on 2024-11-06 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0004_form_sim_fecha_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sim',
            name='fecha_estudio',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 17, 19, 54, 761562), verbose_name='date joined'),
        ),
    ]
