# Generated by Django 4.2.11 on 2024-11-07 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0006_alter_form_sim_fecha_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sim',
            name='fecha_estudio',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 11, 32, 10, 441676), verbose_name='date joined'),
        ),
    ]
