# Generated by Django 4.2.11 on 2024-11-07 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0007_alter_form_sim_fecha_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_sim',
            name='aliaspaciente',
            field=models.CharField(default='testing', max_length=30),
        ),
        migrations.AlterField(
            model_name='form_sim',
            name='fecha_estudio',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 14, 49, 9, 83382), verbose_name='date joined'),
        ),
    ]
