# Generated by Django 4.2.11 on 2024-11-08 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0009_form_sim_idestudio1_alter_form_sim_fecha_estudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('idformulario', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=30)),
                ('archivo', models.FileField(blank=True, default='fallback.pdf', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='form_sim',
            name='fecha_estudio',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 9, 10, 2, 776219), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='form_sim',
            name='idestudio1',
            field=models.CharField(default='30', max_length=30),
        ),
    ]
