# Generated by Django 4.2.11 on 2024-11-20 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0014_alter_form_sim_fecha_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sim',
            name='fecha_estudio',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 7, 6, 51, 841822), verbose_name='date joined'),
        ),
    ]
