# Generated by Django 4.2.11 on 2024-11-22 11:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_paciente_comentario_alter_paciente_etnia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulacion', '0017_alter_form_sim_fecha_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_sim',
            name='aliaspaciente',
        ),
        migrations.RemoveField(
            model_name='form_sim',
            name='estudio1',
        ),
        migrations.RemoveField(
            model_name='form_sim',
            name='fecha_estudio',
        ),
        migrations.RemoveField(
            model_name='form_sim',
            name='idestudio1',
        ),
        migrations.AddField(
            model_name='form_sim',
            name='fecha_simulación',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 8, 18, 33, 634431), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='form_sim',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form_sim',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
