# Generated by Django 4.2.11 on 2024-11-22 11:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_paciente_comentario_alter_paciente_etnia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulacion', '0018_remove_form_sim_aliaspaciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_simulacion', models.DateTimeField(default=datetime.datetime(2024, 11, 22, 8, 24, 41, 866624), verbose_name='date joined')),
                ('comentario', models.CharField(max_length=30)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Form_Sim',
        ),
    ]
