# Generated by Django 4.2.11 on 2024-11-22 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0020_remove_respuesta_idformulario_respuesta_formulario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_simulacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 15, 16, 36, 13471), verbose_name='Fecha de Solicitud'),
        ),
    ]
