# Generated by Django 4.2.11 on 2024-11-24 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0021_alter_respuesta_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_simulacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 18, 48, 31, 439675), verbose_name='Fecha de Solicitud'),
        ),
    ]
