# Generated by Django 4.2.11 on 2024-12-01 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0022_alter_solicitudes_fecha_simulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_simulacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 10, 38, 24, 807514), verbose_name='Fecha de Solicitud'),
        ),
    ]
