# Generated by Django 4.2.11 on 2024-09-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_class',
            field=models.IntegerField(default='1', verbose_name='userclass'),
        ),
    ]
