# Generated by Django 4.2.11 on 2024-09-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_class',
        ),
        migrations.AddField(
            model_name='account',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_investigador',
            field=models.BooleanField(default=True),
        ),
    ]
