# Generated by Django 4.2.11 on 2024-11-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_user_class_account_is_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='especialidad',
            field=models.CharField(blank=True, default='Espcecialidad', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='institucion',
            field=models.CharField(blank=True, default='Institucion', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='matricula',
            field=models.CharField(blank=True, default='Matricula', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=30),
        ),
    ]
