# Generated by Django 4.2.11 on 2024-11-24 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_apellido_account_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=30)),
                ('apellido', models.CharField(default='Apellido', max_length=30)),
                ('especialidad', models.CharField(blank=True, default='Espcecialidad', max_length=30)),
                ('institucion', models.CharField(blank=True, default='Institucion', max_length=30)),
                ('matricula', models.CharField(blank=True, default='Matricula', max_length=30)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_investigador', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
