# Generated by Django 4.2.11 on 2024-09-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_paciente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0, verbose_name='edad'),
        ),
    ]
