# Generated by Django 4.2.11 on 2024-09-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default='asd', max_length=3),
        ),
    ]
