# Generated by Django 4.2.11 on 2024-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_remove_paciente_edad_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.CharField(default='no', max_length=30),
        ),
    ]
