# Generated by Django 4.2.11 on 2024-10-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_alter_paciente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='raza',
            field=models.CharField(default='asd', max_length=30),
        ),
    ]
