# Generated by Django 4.2.11 on 2024-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_alter_paciente_altura_alter_paciente_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='raza',
        ),
        migrations.AddField(
            model_name='paciente',
            name='etnia',
            field=models.CharField(default='nulo', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=3),
        ),
    ]
