# Generated by Django 4.2.11 on 2024-12-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_datoscuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='apellido',
            field=models.CharField(blank=True, default='Apellido', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='nombre',
            field=models.CharField(blank=True, default='Nombre', max_length=30),
        ),
        migrations.AlterField(
            model_name='datoscuenta',
            name='especialidad',
            field=models.CharField(blank=True, default='Especialidad', max_length=30),
        ),
    ]
