# Generated by Django 4.2.11 on 2024-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioUno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('aliaspaciente', models.CharField(max_length=30)),
                ('campo1', models.CharField(default='asd', max_length=3)),
                ('campo2', models.IntegerField(default='0', verbose_name='campo2')),
                ('campo3', models.IntegerField(default='0', verbose_name='campo3')),
            ],
        ),
    ]
