# Generated by Django 4.2.11 on 2024-10-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0002_remove_estudiouno_campo1_remove_estudiouno_campo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiouno',
            name='aliaspaciente',
        ),
        migrations.RemoveField(
            model_name='estudiouno',
            name='idmedico',
        ),
        migrations.AddField(
            model_name='estudiouno',
            name='usuariomed',
            field=models.CharField(default='default', max_length=3),
        ),
    ]
