# Generated by Django 4.2.11 on 2024-10-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0004_remove_estudiouno_tipoestudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiouno',
            name='idpaciente',
        ),
        migrations.AddField(
            model_name='estudiouno',
            name='aliaspaciente',
            field=models.CharField(default='default', max_length=3),
        ),
        migrations.AddField(
            model_name='estudiouno',
            name='tipodeestudio',
            field=models.CharField(default='default', max_length=3),
        ),
    ]
