# Generated by Django 4.2.11 on 2024-10-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0005_remove_estudiouno_idpaciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiouno',
            name='aliaspaciente',
            field=models.CharField(default='zxczxc', max_length=3),
        ),
        migrations.AlterField(
            model_name='estudiouno',
            name='tipodeestudio',
            field=models.CharField(default='qwrqwr', max_length=3),
        ),
        migrations.AlterField(
            model_name='estudiouno',
            name='usuariomed',
            field=models.CharField(default='asd', max_length=3),
        ),
    ]
