# Generated by Django 4.2.11 on 2024-10-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0007_estudio_delete_estudiouno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='tipoEstudio',
            field=models.CharField(default='asd', max_length=30),
        ),
    ]
