# Generated by Django 4.2.11 on 2024-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0008_alter_estudio_tipoestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='imagen',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
