# Generated by Django 4.2.11 on 2024-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0009_estudio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='archivo',
            field=models.FileField(blank=True, default='fallback.pdf', upload_to=''),
        ),
    ]
