# Generated by Django 4.2.11 on 2024-11-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0011_estudio_idpaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='idpaciente',
        ),
    ]
