# Generated by Django 4.2.11 on 2024-11-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_paciente_comentario_alter_paciente_etnia_and_more'),
        ('estudios', '0013_estudio_aliaspaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='aliaspaciente',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='imagen',
        ),
        migrations.AddField(
            model_name='estudio',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
