# Generated by Django 4.2.11 on 2024-09-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nac', models.DateField(verbose_name='nacimiento')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('alias', models.CharField(max_length=30)),
            ],
        ),
    ]
