# Generated by Django 4.2.11 on 2024-09-29 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPacientes',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pacientes.paciente')),
            ],
            bases=('pacientes.paciente',),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nac',
        ),
    ]
