# Generated by Django 4.2.11 on 2024-09-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_adminpacientes_remove_paciente_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
    ]
