# Generated by Django 4.2.11 on 2024-09-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
    ]
