# Generated by Django 4.2.11 on 2024-09-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_remove_paciente_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.CharField(default='no', max_length=30),
        ),
    ]
