# Generated by Django 4.2.11 on 2024-10-10 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_paciente_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.IntegerField(default='0', verbose_name='altura'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default='0', verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacimiento',
            field=models.DateField(default=datetime.date.today, verbose_name='nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(default='0', verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='AdminPacientes',
        ),
    ]
