# Generated by Django 4.2.11 on 2024-11-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0002_form_sim_fecha_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_sim',
            name='fecha_estudio',
        ),
    ]
