# Generated by Django 4.2.11 on 2024-11-20 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0010_respuesta_alter_form_sim_fecha_estudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sim',
            name='fecha_estudio',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 6, 13, 36, 637495), verbose_name='date joined'),
        ),
    ]
