# Generated by Django 4.2.11 on 2024-11-22 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0019_solicitudes_delete_form_sim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='idformulario',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulacion.solicitudes'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_simulacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 13, 9, 53, 651731), verbose_name='Fecha de Solicitud'),
        ),
    ]
