# Generated by Django 4.2.11 on 2024-12-10 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0023_alter_solicitudes_fecha_simulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='comentario',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='comentario',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_simulacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 17, 0, 33, 257278), verbose_name='Fecha de Solicitud'),
        ),
    ]
