# Generated by Django 4.2.11 on 2025-05-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0024_alter_respuesta_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_simulacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 16, 15, 22, 299354), verbose_name='Fecha de Solicitud'),
        ),
    ]
