# Generated by Django 4.2.11 on 2025-05-19 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0026_alter_solicitudes_fecha_simulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_simulacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 16, 17, 1, 886473), verbose_name='Fecha de Solicitud'),
        ),
    ]
