# Generated by Django 4.2.11 on 2025-05-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularios_Ley',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('nacimiento', models.DateField(default=datetime.date.today, verbose_name='nacimiento')),
                ('comentario', models.TextField(blank=True)),
            ],
        ),
    ]
